[build]                                                                                                                                                                                                                                        command = ""
    publish = "."

  [[secrets_scanning.exclusions]]
    path = "js/firebase-config.js"
